Non-uniform quantization of vector norms
facebookresearch/faiss pull request #2037
Opened 2021-09-05 08:19 UTC by KinglittleQ

This diff implemented non-uniform quantization of vector norms in additive quantizers. index_factory and I/O are supported.

index_factory:  `XXX_Ncqint{nbits}` where `nbits` is the number of bits to quantize vector norm.

For 8 bits code, it is almost the same as 8-bit uniform quantization. It will slightly improve the accuracy if the code size is less than 8 bits.
```
RQ4x8_Nqint8:  R@1 0.1116
RQ4x8_Ncqint8: R@1 0.1117

RQ4x8_Nqint4:  R@1 0.0901
RQ4x8_Ncqint4: R@1 0.0989
```

2021-09-06 22:07 UTC, mdouze requested changes
It is on purpose that I did not add a field to set the number of bits for the quantized norm. Could you just support cqint4 and cqint8 and maybe a few others instead of adding a new field for the number of bits in the norm?

2021-09-06 22:07 UTC, mdouze commented on faiss/impl/LocalSearchQuantizer.cpp
> +            clus.train(n, norms.data(), qnorm);
apparently there is a dynamic programming way to solve the 1D k-means.

2021-09-06 22:07 UTC, mdouze commented on faiss/impl/index_read.cpp
> +    READ1(aq->nbits_norm);
please make it backwards compatible by storing the qnorm only for qcint variants

2021-09-07 02:28 UTC, KinglittleQ commented
@mdouze  Sure, I'm going to fix them.

2021-09-07 08:59 UTC, mdouze commented
Very interesting paper about 1D k-means: https://arxiv.org/abs/1701.07204
@KinglittleQ if you want to give a stab at extracting a practical algorithm from it... Otherwise I'll do it at some point.

2021-09-12 12:35 UTC, KinglittleQ commented
@mdouze  I've added 1D K-means as described in sec 2.2 of https://arxiv.org/abs/1701.07204. It is O(kn) in time and O(kn) in space.

2021-09-12 12:44 UTC, KinglittleQ commented
There is a segmentation fault bug in OSX. Maybe I need some time to find out the problem...

2021-09-21 05:11 UTC, KinglittleQ commented
@mdouze PTAL.

2021-09-21 15:06 UTC, mdouze commented
Excellent, will import into faiss' FB version.

2021-09-21 16:18 UTC, mdouze approved these changes

2021-10-11 21:13 UTC, closed without merging