Use RMM current device resource for memory allocation
facebookresearch/faiss pull request #3171
Opened 2023-12-12 16:45 UTC by tarang-jain

2024-01-09 16:35 UTC, bdice approved these changes
This looks fine to me.

2024-01-10 01:07 UTC, cjnolet approved these changes
This LGTM also.

2024-01-10 20:59 UTC, tfeher requested changes
Thanks @tarang-jain for the PR. There are a few issues, but in general the changes related to the current device resource look good.

2024-01-11 07:30 UTC, tarang-jain commented on faiss/gpu/StandardGpuResources.h
> +    rmm::mr::device_memory_resource* mmr;
Changed it back to unique pointer. Added the trailing underscore.

2024-01-11 07:30 UTC, tarang-jain commented on faiss/gpu/StandardGpuResources.cpp
>            mmr(new rmm::mr::managed_memory_resource),
Changed it back to unique pointer, so the an update to the destructor is not needed.

2024-02-06 05:50 UTC, tarang-jain commented
Closing in favour of #3044. These changes have been added to #3044

2024-02-06 05:50 UTC, closed without merging