add skip_storage flag to HNSW
facebookresearch/faiss pull request #3487
Opened 2024-05-29 14:04 UTC by mdouze

Summary:
Sometimes it is not useful to serialize the storage index along with a HNSW index. This diff adds a flag that supports skipping the storage of the index.

Searchign and adding to the index is not possible until a storage index is added back in.

Differential Revision: D57911060

2024-05-29 16:28 UTC, alexanderguzhva requested changes

2024-05-29 16:28 UTC, alexanderguzhva commented on faiss/impl/index_write.cpp
>          write_index(idxhnsw->storage, f);
writing the storage twice, dupilcate rows 770 and 772

2024-05-29 20:44 UTC, junjieqi commented on faiss/impl/index_read.cpp
> +    if (h == fourcc("null")) {
When do we see the caller provide null ?

2024-05-29 20:44 UTC, junjieqi commented on faiss/impl/index_write.cpp
> +            WRITE1(n4);
is it gonna to output in stdout?

2024-05-29 20:44 UTC, junjieqi commented on tests/test_graph_based.py
> +        if False:
where do we define the False?

2024-05-30 16:13 UTC, junjieqi commented
format & internal linter

2024-05-31 21:52 UTC, closed without merging